"""
notify.py — Send an HTML email alert for qualifying job matches.
"""
import json
import logging
import smtplib
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import List, Dict

logger = logging.getLogger(__name__)

# ── HTML email template ────────────────────────────────────────────────────────
_HTML = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<style>
  body    {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Arial, sans-serif;
             line-height: 1.6; color: #222; max-width: 720px; margin: 0 auto; padding: 24px; }}
  h1      {{ color: #0a66c2; border-bottom: 2px solid #0a66c2; padding-bottom: 10px; }}
  .summary {{ background: #f3f6fb; padding: 12px 16px; border-radius: 6px; margin-bottom: 20px; }}
  .card   {{ background: #fafafa; border-left: 5px solid #ccc;
             padding: 16px; margin: 18px 0; border-radius: 4px; }}
  .card.strong {{ border-left-color: #1e8a44; }}
  .card.maybe  {{ border-left-color: #d97706; }}
  .score  {{ font-size: 2em; font-weight: 700; line-height: 1; }}
  .score.strong {{ color: #1e8a44; }}
  .score.maybe  {{ color: #d97706; }}
  .badge  {{ display: inline-block; padding: 2px 10px; border-radius: 99px;
             font-size: 0.78em; font-weight: 600; margin-left: 8px; vertical-align: middle; }}
  .b-strong {{ background: #d1fae5; color: #065f46; }}
  .b-maybe  {{ background: #fef3c7; color: #92400e; }}
  .meta   {{ color: #555; font-size: 0.9em; margin: 6px 0 10px; }}
  .box    {{ padding: 8px 12px; border-radius: 4px; margin: 8px 0; font-size: 0.93em; }}
  .green  {{ background: #d1fae5; }}
  .red    {{ background: #fee2e2; }}
  .btn    {{ display: inline-block; background: #0a66c2; color: #fff;
             padding: 9px 18px; border-radius: 5px; text-decoration: none;
             font-weight: 600; margin-top: 10px; font-size: 0.9em; }}
  .footer {{ color: #aaa; font-size: 0.82em; margin-top: 32px;
             border-top: 1px solid #eee; padding-top: 14px; }}
  ul      {{ margin: 4px 0; padding-left: 20px; }}
</style>
</head>
<body>
<h1>🔍 LinkedIn Job Scout — {date}</h1>
<div class="summary">
  Found <strong>{total}</strong> job{plural} above your <strong>{threshold}%</strong> fit threshold.
  ({strong_count} strong &nbsp;·&nbsp; {maybe_count} possible)
</div>

{cards}

<div class="footer">
  Generated by your local LinkedIn Job Scout Agent &nbsp;·&nbsp;
  Powered by Claude Sonnet &nbsp;·&nbsp; Scores are LLM estimates — use as triage only.
</div>
</body>
</html>
"""

_CARD = """\
<div class="card {verdict}">
  <div>
    <span class="score {verdict}">{fit_score}</span><small style="font-size:0.5em;color:#888">/100</small>
    <span class="badge b-{verdict}">{verdict_label}</span>
  </div>
  <h2 style="margin:8px 0 4px">
    <a href="{url}" style="color:#222;text-decoration:none;">{title}</a>
  </h2>
  <div class="meta">🏢 {company} &nbsp;·&nbsp; 📍 {location}</div>
  {reasons_html}
  {concerns_html}
  <a class="btn" href="{url}">View on LinkedIn →</a>
</div>
"""


def _parse(val) -> list:
    """Accept either a Python list or a JSON string; always return a list."""
    if isinstance(val, list):
        return val
    if isinstance(val, str):
        try:
            return json.loads(val)
        except Exception:
            return [val] if val else []
    return []


def _build_card(job: Dict) -> str:
    verdict = (job.get("verdict") or "maybe").lower()
    reasons  = _parse(job.get("reasons",  []))
    concerns = _parse(job.get("concerns", []))

    def _ul(items, limit=3):
        return "<ul>" + "".join(f"<li>{i}</li>" for i in items[:limit]) + "</ul>"

    reasons_html  = f'<div class="box green"><strong>✓ Fit:</strong>{_ul(reasons)}</div>'  if reasons  else ""
    concerns_html = f'<div class="box red"><strong>⚠ Concerns:</strong>{_ul(concerns)}</div>' if concerns else ""

    labels = {"strong": "Strong Match", "maybe": "Possible Match", "weak": "Weak Match"}

    return _CARD.format(
        fit_score=job.get("fit_score", 0),
        verdict=verdict,
        verdict_label=labels.get(verdict, verdict.title()),
        title=job.get("title", "Untitled"),
        company=job.get("company", "Unknown Company"),
        location=job.get("location", "Unknown Location"),
        url=job.get("url", "#"),
        reasons_html=reasons_html,
        concerns_html=concerns_html,
    )


def send_alert(
    jobs: List[Dict],
    smtp_host: str,
    smtp_port: int,
    smtp_user: str,
    smtp_password: str,
    from_email: str,
    to_email: str,
    threshold: int = 60,
) -> None:
    if not jobs:
        logger.info("No jobs to email.")
        return

    strong_count = sum(1 for j in jobs if (j.get("verdict") or "") == "strong")
    maybe_count  = len(jobs) - strong_count
    date_str     = datetime.now().strftime("%B %d, %Y")

    html_body = _HTML.format(
        date=date_str,
        total=len(jobs),
        plural="s" if len(jobs) != 1 else "",
        threshold=threshold,
        strong_count=strong_count,
        maybe_count=maybe_count,
        cards="\n".join(_build_card(j) for j in jobs),
    )

    # Plain-text fallback
    text_lines = [f"Job Scout Report — {date_str}", ""]
    for j in jobs:
        text_lines += [
            f"[{j.get('fit_score', 0)}/100 {j.get('verdict', '')}]  "
            f"{j.get('title', '')} @ {j.get('company', '')}",
            f"  {j.get('location', '')}",
            f"  {j.get('url', '')}",
            "",
        ]
    text_body = "\n".join(text_lines)

    # Compose message
    msg = MIMEMultipart("alternative")
    subject_tag = f"{strong_count}✓ {maybe_count}?" if maybe_count else f"{strong_count} strong"
    msg["Subject"] = f"🔍 Job Scout [{subject_tag}] — {date_str}"
    msg["From"]    = from_email
    msg["To"]      = to_email
    msg.attach(MIMEText(text_body, "plain"))
    msg.attach(MIMEText(html_body, "html"))

    try:
        with smtplib.SMTP(smtp_host, smtp_port, timeout=30) as server:
            server.ehlo()
            server.starttls()
            server.login(smtp_user, smtp_password)
            server.sendmail(from_email, [to_email], msg.as_string())
        logger.info("✉  Email sent to %s — %d job(s)", to_email, len(jobs))
    except Exception as e:
        logger.error("Failed to send email: %s", e)
        raise
